### ISSUE TITLE
Install fails on step 3: GetAuthenticationToken

### ISSUE THREAD

**Issue by Mikebrp** [CrowdStrike/aws-ssm-distributor#39]
Hello thanks for offering this automation.  I'm receiving a failure during step 3 GetAuthenticationToken.  I was hoping the team could offer some assistance with this issue thanks!  Below are the failure details from that step.

```
Traceback (most recent call last):
  File "/tmp/ccd53296-10ec-4444-8d96-18c474718271-2023-06-08-18-31-05/customer_script.py", line 38, in script_handler
    conn.request('POST', '/oauth2/token', params, headers)
  File "/var/lang/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/var/lang/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/var/lang/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/var/lang/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/var/lang/lib/python3.7/http/client.py", line 1443, in connect
    super().connect()
  File "/var/lang/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/var/lang/lib/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/var/lang/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/ccd53296-10ec-4444-8d96-18c474718271-2023-06-08-18-31-05/customer_script.py", line 48, in script_handler
    raise ValueError('Failure while interacting with Crowdstrike backend. Error: {}'.format(e))
ValueError: Failure while interacting with Crowdstrike backend. Error: [Errno -2] Name or service not known

ValueError - Failure while interacting with Crowdstrike backend. Error: [Errno -2] Name or service not known`
`Step fails when it is Poll action status for completion. Traceback (most recent call last): File "/tmp/ccd53296-10ec-4444-8d96-18c474718271-2023-06-08-18-31-05/customer_script.py", line 38, in script_handler conn.request('POST', '/oauth2/token', params, headers) File "/var/lang/lib/python3.7/http/client.py", line 1281, in request self._send_request(method, url, body, headers, encode_chunked) File "/var/lang/lib/python3.7/http/client.py", line 1327, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/var/lang/lib/python3.7/http/client.py", line 1276, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/var/lang/lib/python3.7/http/client.py", line 1036, in _send_output self.send(msg) File "/var/lang/lib/python3.7/http/client.py", line 976, in send self.connect() File "/var/lang/lib/python3.7/http/client.py", line 1443, in connect super().connect() File "/var/lang/lib/python3.7/http/client.py", line 948, in con...
```

Any help or insight would be appreciated.

**Comment by ffalor** [comment]
This error looks like the either no value or the wrong value was stored in the Cloud ssm parameter store parameter.

Can you verify:

1. you stored the cloud value in ssm parameter store? Default location is /CrowdStrike/Falcon/Cloud
2. the value of the parameter is correct
3. the `FalconCloud` input parameter is pointing to the correct ssm parameter value. Default location is /CrowdStrike/Falcon/Cloud

**Comment by Mikebrp** [comment]
Awesome thanks for pointing me at this.  It looks like I had https://api.us-2.crowdstrike.com/ in that parameter instead of https://api.us-2.crowdstrike.com changing that resolved the issue.  Thanks!

**Comment by ffalor** [comment]
@Mikebrp awesome glad it was an easy fix. Thanks for letting me know.
