### ISSUE TITLE
(custom-binary-package) KeyError: 'resources'

### ISSUE THREAD

**Issue by xomgc3** [CrowdStrike/aws-ssm-distributor#80]
I ensured that I had the latest code today and wanted to get the latest binary packages.  However, I ran into 2 errors:

```
% python3 create-package.py -r us-east-2 -b foo
Downloading required files...
Traceback (most recent call last):
  File "<snip>/aws-ssm-distributor/custom-binary-package/package/create-package.py", line 202, in <module>
    resources = sensors["body"]["resources"]
KeyError: 'resources'
```

Also, the `distro` package is missing:

```
% python3 create-package.py -r us-east-2 -b foo
Traceback (most recent call last):
  File "<snip>/aws-ssm-distributor/custom-binary-package/package/create-package.py", line 10, in <module>
    from distro import major_version
ModuleNotFoundError: No module named 'distro'
```

**Comment by ffalor** [comment]
Thank you for reporting, I am looking into it

**Comment by ffalor** [comment]
Hey @xomgc3 sorry for the trouble. I've removed the unneeded distro import & added some logging to the download of the sensor where you got the error.

Can you run it again and see what we get back? Also there were a good amount of changes to this recently to add support for all of our operating systems so the most recent script expects things like agent_list.json etc to have a specific value. This removes the need for customers to maintain this to add more operating systems etc.

I ran it locally w/o issue:

<details>
  <summary>Run Log</summary>
  
  ### Heading
 ```shell
python3 create-package.py -r us-east-1 -b bucket        
Downloading required files...
Downloading falcon-sensor-7.04.0-15907.amzn1.x86_64.rpm for Amazon Linux 1
Downloading falcon-sensor-7.04.0-15907.amzn2.x86_64.rpm for Amazon Linux 2
Downloading falcon-sensor-7.04.0-15907.amzn2.aarch64.rpm for Amazon Linux 2 - arm64
Downloading falcon-sensor-7.04.0-15907.amzn2023.x86_64.rpm for Amazon Linux 2023
Downloading falcon-sensor-7.04.0-15907.amzn2023.aarch64.rpm for Amazon Linux 2023 - arm64
Downloading falcon-sensor-7.04.0-15907.el6.x86_64.rpm for RHEL/CentOS/Oracle 6
Downloading falcon-sensor-7.04.0-15907.el7.x86_64.rpm for RHEL/CentOS/Oracle 7
Downloading falcon-sensor-7.04.0-15907.el8.x86_64.rpm for RHEL/CentOS/Oracle 8
Downloading falcon-sensor-7.04.0-15907.el8.aarch64.rpm for RHEL/CentOS 8 - arm64
Downloading falcon-sensor-7.04.0-15907.el9.x86_64.rpm for RHEL/Oracle 9
Downloading falcon-sensor-7.04.0-15907.el9.aarch64.rpm for RHEL 9 - arm64
Downloading falcon-sensor-7.04.0-15907.el6.x86_64.rpm for RHEL/CentOS/Oracle 6
Downloading falcon-sensor-7.04.0-15907.el7.x86_64.rpm for RHEL/CentOS/Oracle 7
Downloading falcon-sensor-7.04.0-15907.el8.x86_64.rpm for RHEL/CentOS/Oracle 8
Downloading falcon-sensor-7.04.0-15907.el8.aarch64.rpm for RHEL/CentOS 8 - arm64
Downloading falcon-sensor-7.04.0-15907.el6.x86_64.rpm for RHEL/CentOS/Oracle 6
Downloading falcon-sensor-7.04.0-15907.el7.x86_64.rpm for RHEL/CentOS/Oracle 7
Downloading falcon-sensor-7.04.0-15907.el8.x86_64.rpm for RHEL/CentOS/Oracle 8
Downloading falcon-sensor-7.04.0-15907.suse11.x86_64.rpm for SLES 11
Downloading falcon-sensor-7.04.0-15907.suse12.x86_64.rpm for SLES 12
Downloading falcon-sensor-7.04.0-15907.suse15.x86_64.rpm for SLES 15
Downloading falcon-sensor_7.04.0-15907_amd64.deb for Ubuntu 14/16/18/20/22
Downloading falcon-sensor_7.04.0-15907_arm64.deb for Ubuntu 18/20/22 - arm64
Downloading falcon-sensor_7.04.0-15907_amd64.deb for Debian 9/10/11
Downloading WindowsSensor.MaverickGyr.exe for Windows 
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
INFO     Found credentials in shared credentials file: ~/.aws/credentials
Bucket already exists:
Uploading file ./s3-bucket/CS_CENTOS6_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.6177070140838623s
Uploading file ./s3-bucket/CS_RHEL9_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 0.9604897499084473s
Uploading file ./s3-bucket/CS_SLES15_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.0052878856658936s
Uploading file ./s3-bucket/CS_CENTOS8_ARM64.zip:
Successfully finished uploading files to s3 bucket. Took 0.450991153717041s
Uploading file ./s3-bucket/CS_AMAZON2023_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.2047691345214844s
Uploading file ./s3-bucket/CS_RHEL8_ARM64.zip:
Successfully finished uploading files to s3 bucket. Took 0.4805879592895508s
Uploading file ./s3-bucket/CS_SLES11_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.051734447479248s
Uploading file ./s3-bucket/CS_ORACLE7_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 0.9522552490234375s
Uploading file ./s3-bucket/CS_DEBIAN_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.1441287994384766s
Uploading file ./s3-bucket/CS_CENTOS7_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.1827800273895264s
Uploading file ./s3-bucket/CS_CENTOS8_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.219865322113037s
Uploading file ./s3-bucket/CS_ORACLE6_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.0502734184265137s
Uploading file ./s3-bucket/CS_AMAZON2_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 0.9649968147277832s
Uploading file ./s3-bucket/CS_RHEL8_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.0027077198028564s
Uploading file ./s3-bucket/CS_RHEL9_ARM64.zip:
Successfully finished uploading files to s3 bucket. Took 0.47113943099975586s
Uploading file ./s3-bucket/CS_AMAZON2023_ARM64.zip:
Successfully finished uploading files to s3 bucket. Took 0.4238724708557129s
Uploading file ./s3-bucket/CS_UBUNTU_ARM64.zip:
Successfully finished uploading files to s3 bucket. Took 0.3814241886138916s
Uploading file ./s3-bucket/CS_SLES12_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 0.9867458343505859s
Uploading file ./s3-bucket/CS_AMAZON_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 0.9173212051391602s
Uploading file ./s3-bucket/CS_AMAZON2_ARM64.zip:
Successfully finished uploading files to s3 bucket. Took 0.5662975311279297s
Uploading file ./s3-bucket/CS_RHEL6_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.074159860610962s
Uploading file ./s3-bucket/manifest.json:
Successfully finished uploading files to s3 bucket. Took 0.08609652519226074s
Uploading file ./s3-bucket/CS_UBUNTU_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.0660948753356934s
Uploading file ./s3-bucket/CS_ORACLE8_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 1.0642726421356201s
Uploading file ./s3-bucket/CS_WINDOWS.zip:
Successfully finished uploading files to s3 bucket. Took 2.517408609390259s
Uploading file ./s3-bucket/CS_RHEL7_x86_64.zip:
Successfully finished uploading files to s3 bucket. Took 0.9510879516601562s
Package file have been built and uploaded successfully.
Creating distributor package in us-east-1
Created ssm package CrowdStrike-FalconSensor:
Distributor package has been built successfully.
Cleaning up files...
Package CrowdStrike-FalconSensor created successfully in region us-east-1.
 ```
</details>

**Comment by ffalor** [comment]
When you log into the console and go to Host Setup & Management > Sensor Downloads do you see a entry for Amazon 1? That filter is valid. 

Would you mind replacing your script with this one: https://gist.github.com/ffalor/5197aa421871e8fc35c889a9f747291e and giving me the output minus any sensitive info

It adds more logging incase the issue is something else other than the filter returning no results.

**Comment by ffalor** [comment]
Awesome, thank you for your feedback great find. I'll add some error handling to properly account for this scenario
